### PR TITLE
Portfolio layout in divs

### PR DESCRIPTION
**Pull request by MonikaFu**
This PR:
* re-organizes portfolio level view
* modifies pie annotation text slightly

NOTE: 
* table does not look great at the moment but I leave improving of it's layout for another PR #53 
* consider if map should be removed from the view as it requires selectors as potentially the only plot in this view #54

### CODE REVIEW

**Comment by jdhoffa** [comment]
This PR seems to introduce a bug. 
Repro steps: 
* Spin up the dashboard
* Select the Portfolio-Level tab
* Bug: Try to select any other tab, and you won't be able to

(Note: the reverse is not true. I can select Sector-Level and Company-Level tabs back and forth as many times as I like, this is limited to the portfolio layout)

**Comment by MonikaFu** [comment]
@jdhoffa bug is fixed

**Comment by jdhoffa** [comment]
@MonikaFu given that you are already removing the Map in this PR, I can't approve it until a decision is made on https://github.com/RMI-PACTA/pacta-dashboard-svelte/issues/54

If you want to merge this, then please add the map back. Otherwise, it must wait.

**Comment by MonikaFu** [comment]
@jdhoffa added map back

**Review by jdhoffa — APPROVED** [review]
looks good to me!

**Pull request merged**
