### PR TITLE
✨ gains content for introduction

### PR DESCRIPTION
**Pull request by jdhoffa**
- [x] Add icons (if we want them, somewhat relates to #108) -> https://github.com/RMI-PACTA/pacta-dashboard-svelte/issues/131
- [x] Add hyperlinks, bolding, italics, etc. when relevant
- [x] Probably other things

### CODE REVIEW

**Comment by cjyetman** [comment]
FYI... it does not appear to one in draft mode

**Comment by jdhoffa** [comment]
> FYI... it does not appear to one in draft mode

Woops! Indeed apologies, this is ready for review now. All todos have been dealt with (and one new issue has been opened to track the icon discussion).

**Review by cjyetman — APPROVED** [review]
did not review content, otherwise changes seem reasonable
tested locally and intro page gains text and accordion thing, and I don't see any problems

note: one weirdness I saw was that the last (Disclaimers...) accordion item seems to open by default, whereas it might make more sense for the 1st accordion item (About PACTA) to be the default open one

**Comment by jdhoffa** [comment]
> note: one weirdness I saw was that the last (Disclaimers...) accordion item seems to open by default, whereas it might make more sense for the 1st accordion item (About PACTA) to be the default open one

good catch! fixed that

**Review by cjyetman — APPROVED** [review]
🚀 About PACTA section now opens by default

**Pull request merged**
