### PR TITLE
Add company-level techmix

### PR DESCRIPTION
**Pull request by MonikaFu**
Here I add the company-level techmix to the company-level page. As with bubble it is not fully wired up but I will figure it out once I deal with the filters.

### CODE REVIEW

**Comment by jdhoffa** [comment]
It seems that the company names and weights aren't rendering/ appearing in the plot, is that intentional?
Screenshot 2024-08-23 at 12 26 01

**Comment by MonikaFu** [comment]
@jdhoffa this is strange because they do render for me
image

**Comment by jdhoffa** [comment]
Ah it seems to be a light-mode/ dark-mode issue. 
The names render in light-mode, but not in dark-mode!

Relates to #32

**Review by jdhoffa — APPROVED** [review]

**Comment by MonikaFu** [comment]
so strange! But good to know! We'll tackle it in #32 then!

**Pull request merged**
