### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by AlexAxthelm**
- Update Docker container structure
  - Remove dependence on `nginx` for build process (moved to separate container)
  - Update `docker-compose` file to have server start if build process succeeds
- Clarify paths: rename `src/json/` to `src/data/` 
- Isolate data inputs: Move contents of `src/json/` to `sample-data/`
  - **NOTE:** This means that local build will fail unless those files are copied back into `/src/data/`

### CODE REVIEW

**Comment by jdhoffa** [comment]
Pulled locally and: 
* Confirmed that **after I copied the contents of `sample-data` to `src/data`**, I can run the app locally using `vite build` and `vite preview`
* Confrimed that running `docker-compose up --build` and the navigating to `localhost:3000`, also serves the dashboard as expected

**Comment by jdhoffa** [comment]
@AlexAxthelm I see this is still in draft mode, but you have requested a review already. Is there anything particular you want me to focus this preliminary review on?

**Review by MonikaFu — CHANGES_REQUESTED** [review]
@AlexAxthelm can we bring back `tech_order_in_sectors.json` back to the `\json` folder? It's a fixed file, it is not generated by `workflow.pacta.dashboard`. I think it makes sense that it lives in the `json` folder. The same would hold for map data but we're going to remove the map from the dashboard so it does not matter.

**Comment by jdhoffa** [comment]
For visibility:
https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/81 will likely change our strategy here (for the better)
FYI @AlexAxthelm

**Comment by AlexAxthelm** [comment]
Closing in favor of #109, rather than resolving conflicts.

**Pull request closed without merging**
