### PR TITLE
emissions timeline adapts to selected scenario

### LINKED ISSUE #41: feat: Emission intensity plot has a selectable scenario source and scenario
- depends on https://github.com/RMI-PACTA/workflow.pacta.dashboard/pull/40 (https://github.com/RMI-PACTA/workflow.pacta.dashboard/pull/26 was superseded)

Currently we fix a scenario in the plot but because we now have global selectors it makes more sense to make it possible for the user to select a scenario they want to view in this plot. 

AB#11938

### PR DESCRIPTION
**Pull request by cjyetman**
- depends on https://github.com/RMI-PACTA/workflow.pacta.dashboard/pull/40
- closes #41

Allows the emissions intensity timeline plot to react to changes in the scenario and scenario source selectors.

- requires new `data_emissions.json` that includes data for all scenario and scenario source combinations created with [workflow.pacta.dashboard](https://github.com/RMI-PACTA/workflow.pacta.dashboard) after https://github.com/RMI-PACTA/workflow.pacta.dashboard/pull/40 merges (a preliminary example of that included in this PR at `sample-data/data_emissions.json`)
- adapts appropriate event listeners in `src/routes/sector_view.svelte` to the retrigger the emissions timeline plot when the scenario or scenario source selector is changed
- adapts the `time_line.js` to filter the data by scenario and scenario source also, and adds the currently selected scenario source to the legend label

Screenshot 2024-12-05 at 10 26 06

### CODE REVIEW

**Review by jdhoffa — COMMENTED** [review]
I have tested this in coordination with https://github.com/RMI-PACTA/workflow.pacta.dashboard/pull/40

and proved to myself that it works as expected. 

However, @cjyetman I will need to push a styling PR to get CI to pass. Do you mind?

**Comment by cjyetman** [comment]
> However, @cjyetman I will need to push a styling PR to get CI to pass. Do you mind?

go for it

**Review by jdhoffa — APPROVED** [review]
70,000 LINES CHANGED!?
What is this a PR FOR GIANTS

**Comment by jdhoffa** [comment]
> > 70,000 LINES CHANGED!? What is this a PR FOR GIANTS
> 
> 70,596 of it is a completely new sample data file which I mentioned in the description


ahaha i know I was just teasing!! :-)

**Pull request merged**
