### PR TITLE
Remove map and unused techexposure 

### LINKED ISSUE #54: feat: consider if map should be permanently removed
If it was not for the map plot, the portfolio-level overview would not need any selectors in plots which makes a lot of sense since it is an overview and not a deep-dive. Additionally it would shorten the page substantially without cutting off info that is particularly useful. Finally, it would decrease our dependencies on external packages and datasets containing geospacial information.

See #52 for where the change occurred tentatively.

### PR DESCRIPTION
**Pull request by MonikaFu**
ADO decision: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_sprints/taskboard/P4I/2DegreesInvesting/2024_24?workitem=11661

closes #54

### CODE REVIEW

**Comment by jdhoffa** [comment]
@MonikaFu has a decision been made on this already? Can you please link the ADO ticket that documented the decision to remove the map?

**Comment by MonikaFu** [comment]
@jdhoffa it has. See updated description with ADO ticket

**Comment by jdhoffa** [comment]
Thank you!

**Review by jdhoffa — APPROVED** [review]
woohoo!

**Comment by MonikaFu** [comment]
@cjyetman I added you as a reviewer as @jdhoffa is off and I need this merged in before I start working on styling the dashboard. The change has already been approved by @jdhoffa and the only thing that has changed since then is that I merged in the `main` branch. Would be great is you could approve <3

**Review by jdhoffa — APPROVED** [review]

**Pull request merged**
